### ISSUE TITLE
NameError when importing files

### ISSUE THREAD

**Issue by Ruud48** [evanplaice/pypreprocessor#20]
Great program, many thanks for creating it!
I always get a NameError when using import, see:

# python program for testing the pypreprocessor, generates the following error after running: python mime-master.py

# Traceback (most recent call last):
#   File "C:\Raspberry Shake\Source\pypreprocessor.py", line 339, in on_the_fly
#     exec(f.read())
#   File "<string>", line 39, in <module>
#   File "mime-master.py", line 17, in send_email
# NameError: name 'MIMEMultipart' is not defined

#exclude
from pypreprocessor import pypreprocessor
pypreprocessor.output = 'mime-smtp.py'
pypreprocessor.removeMeta = True
pypreprocessor.parse()
#endexclude

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
import sys

user_password = '????????'        # Will give 'Could not login error' but that's okay
from_user = 'xxxxxxx@yyyyyy.com'  
to_user   = from_user   

def send_email():
    global message
    msg = MIMEMultipart()
    msg['Subject'] = 'xxx'
    msg['From'] = from_user
    msg['To'] = to_user
    msg.attach(MIMEText(message))
    try:
        mailServer = smtplib.SMTP('smtp-mail.outlook.com', 587)        # Outlook and Hotmail server
        mailServer.ehlo()
        mailServer.starttls()
        mailServer.login(from_user, user_password)
    except:
        print ('\nERROR: Could not login to mail server! \n')
        mailServer.quit()
        return        
    try:    
        mailServer.sendmail(from_user, to_user, msg.as_string())
    except:
        print ('\nERROR: Could not send email! \n')
    mailServer.quit()
    return

message = 'Test Message 1 '
send_email()
print('Ready')

**Comment by Ruud48** [comment]
All my problems disappeared when I changed my program to use the "if __name__ == '__main__':" which I was not using before.
